name: dka-microservices-staffing-ems

services:
  app:
    image: node:alpine
    container_name: dka-microservices-staffing-ems-app
    hostname: ems.staffing.services.dkaapis.com
    working_dir: /home/app
    logging:
      driver: local
      options:
        max-size: 10m
        max-file: 10
    environment:
      NODE_ENV: development
      DKA_DB_MONGO_HOST: server.dkaapis.com
      DKA_DB_MONGO_USERNAME: developer
      DKA_DB_MONGO_PASSWORD: Cyberhack2010
      ##-----------------------------------------------------
      DKA_HOST_ACCOUNT_SERVICE: account.services.dkaapis.com
      DKA_PORT_ACCOUNT_SERVICE: 80
      ##-----------------------------------------------------
    deploy:
      resources:
        limits:
          memory: 800M
        reservations:
          memory: 500M
    restart: always
    volumes:
      - type: bind
        source: .
        target: /home/app
      - type: bind
        source: ./../../node_modules
        target: /home/app/node_modules
      - type: bind
        source: ./.config
        target: /home/.config
      - type: bind
        source: ./../../yarn.lock
        target: /home/app/yarn.lock
    command: yarn run start:dev
    networks:
      - default
      - dka-microservice-external

  mongo:
    image: mongo:latest
    profiles:
      - db
    container_name: <your-container-name>
    hostname: <your-container-hostname-name>
    environment:
      MONGO_INITDB_ROOT_USERNAME: <username>
      MONGO_INITDB_ROOT_PASSWORD: <password>
    logging:
      driver: local
      options:
        max-size: 10m
        max-file: 10
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 300M
        reservations:
          cpus: '0.25'
          memory: 100M
    restart: always
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        host_ip: 0.0.0.0
    volumes:
      - type: volume
        source: mongodb-data
        target: /data/db
      - type: bind
        source: ./.config/mongo/mongod.conf
        target: /etc/mongod.conf
        read_only: true
    command: mongod --config /etc/mongod.conf
    networks:
      - default
      - dka-microservice-external

volumes:
  mongodb-data:
    driver: local
  dka-ssl-data:
    driver: local

networks:
  default:
    driver: bridge
  dka-microservice-external:
    external: true